config/routes.rb
Devices::Engine.routes.draw do
  resources :devices
  root to: "devices#index"
end

app/models/devices/device.rb
module Devices
  class Device < ActiveRecord::Base
  end
end

app/controllers/devices/application_controller.rb
module Devices
  class ApplicationController < ActionController::Base
  end
end

app/controllers/devices/devices_controller.rb
require_dependency "devices/application_controller"

module Devices
  class DevicesController < ApplicationController
    before_action :set_device, only: [:show, :edit, :update, :destroy]

    # GET /devices
    def index
      @devices = Device.all
    end

    # GET /devices/1
    def show
    end

    # GET /devices/new
    def new
      @device = Device.new
    end

    # GET /devices/1/edit
    def edit
    end

    # POST /devices
    def create
      @device = Device.new(device_params)

      if @device.save
        redirect_to @device, notice: 'Device was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /devices/1
    def update
      if @device.update(device_params)
        redirect_to @device, notice: 'Device was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /devices/1
    def destroy
      @device.destroy
      redirect_to devices_url, notice: 'Device was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_device
        @device = Device.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def device_params
        params.require(:device).permit(:uuid, :device_token, :platform, :endpoint_arn)
      end
  end
end

app/helpers/devices/application_helper.rb
module Devices
  module ApplicationHelper
  end
end

app/helpers/devices/devices_helper.rb
module Devices
  module DevicesHelper
  end
end

app/views/devices/devices/_form.html.erb
<%= form_for(@device) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uuid %><br>
    <%= f.text_field :uuid %>
  </div>
  <div class="field">
    <%= f.label :device_token %><br>
    <%= f.text_field :device_token %>
  </div>
  <div class="field">
    <%= f.label :platform %><br>
    <%= f.text_field :platform %>
  </div>
  <div class="field">
    <%= f.label :endpoint_arn %><br>
    <%= f.text_area :endpoint_arn %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/devices/devices/edit.html.erb
<h1>Editing Device</h1>

<%= render 'form' %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/devices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Devices</h1>

<table>
  <thead>
    <tr>
      <th>Uuid</th>
      <th>Device token</th>
      <th>Platform</th>
      <th>Endpoint arn</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= device.uuid %></td>
        <td><%= device.device_token %></td>
        <td><%= device.platform %></td>
        <td><%= device.endpoint_arn %></td>
        <td><%= link_to 'Show', device %></td>
        <td><%= link_to 'Edit', edit_device_path(device) %></td>
        <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Device', new_device_path %>

app/views/devices/devices/new.html.erb
<h1>New Device</h1>

<%= render 'form' %>

<%= link_to 'Back', devices_path %>

app/views/devices/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uuid:</strong>
  <%= @device.uuid %>
</p>

<p>
  <strong>Device token:</strong>
  <%= @device.device_token %>
</p>

<p>
  <strong>Platform:</strong>
  <%= @device.platform %>
</p>

<p>
  <strong>Endpoint arn:</strong>
  <%= @device.endpoint_arn %>
</p>

<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>

app/views/layouts/devices/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Devices</title>
  <%= stylesheet_link_tag    "devices/application", media: "all" %>
  <%= javascript_include_tag "devices/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>